-- =============================================================================
-- FIX HEAD_COACH DEFAULTS
-- =============================================================================
-- This migration is no longer needed.
-- The grundlagen_completed and is_match_ready columns have been removed.
-- =============================================================================
