-- ============================================
-- Guardian Link Via Code Functions
-- ============================================
-- These functions allow guardians to link to their children
-- using codes generated by coaches/trainers
-- ============================================

-- ============================================
-- Function 1: Preview child by code (without marking as used)
-- Used to show child info before confirming link
-- ============================================
CREATE OR REPLACE FUNCTION validate_child_login_code(
    p_code TEXT
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_code_record RECORD;
    v_child_profile RECORD;
BEGIN
    -- Normalize code (uppercase, trim)
    p_code := UPPER(TRIM(p_code));

    -- Find the code (but don't mark as used yet - that's for login or linking)
    SELECT * INTO v_code_record
    FROM child_login_codes
    WHERE code = p_code
    AND used_at IS NULL
    AND expires_at > now()
    AND failed_attempts < 5;

    IF NOT FOUND THEN
        -- Check if code exists but is invalid (for better error message)
        SELECT * INTO v_code_record
        FROM child_login_codes
        WHERE code = p_code;

        IF FOUND THEN
            IF v_code_record.used_at IS NOT NULL THEN
                RETURN json_build_object('valid', FALSE, 'error', 'Code wurde bereits verwendet');
            ELSIF v_code_record.expires_at <= now() THEN
                RETURN json_build_object('valid', FALSE, 'error', 'Code ist abgelaufen');
            ELSIF v_code_record.failed_attempts >= 5 THEN
                RETURN json_build_object('valid', FALSE, 'error', 'Zu viele Fehlversuche. Bitte neuen Code generieren.');
            END IF;
        END IF;

        RETURN json_build_object('valid', FALSE, 'error', 'Ungültiger Code');
    END IF;

    -- Get child profile
    SELECT * INTO v_child_profile
    FROM profiles
    WHERE id = v_code_record.child_id;

    IF NOT FOUND THEN
        RETURN json_build_object('valid', FALSE, 'error', 'Kind nicht gefunden');
    END IF;

    -- Return child info for preview (don't mark code as used yet)
    RETURN json_build_object(
        'valid', TRUE,
        'child', json_build_object(
            'id', v_child_profile.id,
            'first_name', v_child_profile.first_name,
            'last_name', v_child_profile.last_name,
            'birthdate', v_child_profile.birthdate,
            'avatar_url', v_child_profile.avatar_url
        )
    );

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object(
        'valid', FALSE,
        'error', SQLERRM
    );
END;
$$;

-- ============================================
-- Function 2: Link guardian to child via code
-- This validates the code, creates the link, and marks code as used
-- ============================================
CREATE OR REPLACE FUNCTION link_guardian_via_code(
    p_code TEXT
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_guardian_id UUID;
    v_code_record RECORD;
    v_child_profile RECORD;
    v_existing_link RECORD;
    v_guardian_profile RECORD;
BEGIN
    v_guardian_id := auth.uid();

    IF v_guardian_id IS NULL THEN
        RETURN json_build_object('success', FALSE, 'error', 'Nicht angemeldet');
    END IF;

    -- Normalize code
    p_code := UPPER(TRIM(p_code));

    -- Find valid code
    SELECT * INTO v_code_record
    FROM child_login_codes
    WHERE code = p_code
    AND used_at IS NULL
    AND expires_at > now()
    AND failed_attempts < 5;

    IF NOT FOUND THEN
        -- Increment failed attempts if code exists
        UPDATE child_login_codes
        SET failed_attempts = failed_attempts + 1
        WHERE code = p_code;

        RETURN json_build_object('success', FALSE, 'error', 'Ungültiger oder abgelaufener Code');
    END IF;

    -- Get child profile
    SELECT * INTO v_child_profile
    FROM profiles
    WHERE id = v_code_record.child_id;

    IF NOT FOUND THEN
        RETURN json_build_object('success', FALSE, 'error', 'Kind nicht gefunden');
    END IF;

    -- Check if guardian is already linked to this child
    SELECT * INTO v_existing_link
    FROM guardian_links
    WHERE guardian_id = v_guardian_id
    AND child_id = v_child_profile.id;

    IF FOUND THEN
        -- Still mark code as used
        UPDATE child_login_codes
        SET used_at = now()
        WHERE id = v_code_record.id;

        RETURN json_build_object(
            'success', TRUE,
            'child_id', v_child_profile.id,
            'message', 'Du bist bereits als Vormund für dieses Kind registriert'
        );
    END IF;

    -- Create guardian link
    INSERT INTO guardian_links (
        guardian_id,
        child_id,
        relationship,
        is_primary,
        consent_given_at,
        consent_version
    ) VALUES (
        v_guardian_id,
        v_child_profile.id,
        'parent',
        TRUE,
        now(),
        '1.0'
    );

    -- Mark code as used
    UPDATE child_login_codes
    SET used_at = now()
    WHERE id = v_code_record.id;

    -- Update guardian's profile to mark as guardian if not already
    UPDATE profiles
    SET
        is_guardian = TRUE,
        account_type = CASE
            WHEN account_type = 'standard' THEN 'guardian'
            ELSE account_type
        END
    WHERE id = v_guardian_id;

    -- Update child's guardian_id reference if empty
    UPDATE profiles
    SET guardian_id = v_guardian_id
    WHERE id = v_child_profile.id
    AND guardian_id IS NULL;

    RETURN json_build_object(
        'success', TRUE,
        'child_id', v_child_profile.id,
        'child_name', v_child_profile.first_name || ' ' || COALESCE(v_child_profile.last_name, ''),
        'message', 'Kind erfolgreich verknüpft'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION validate_child_login_code TO anon;
GRANT EXECUTE ON FUNCTION validate_child_login_code TO authenticated;
GRANT EXECUTE ON FUNCTION link_guardian_via_code TO authenticated;

-- ============================================
-- Verification
-- ============================================
DO $$
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Guardian Link Via Code Functions Applied!';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Functions created:';
    RAISE NOTICE '  - validate_child_login_code (updated to return child preview)';
    RAISE NOTICE '  - link_guardian_via_code (new - links guardian via code)';
    RAISE NOTICE '========================================';
END $$;
