-- ============================================
-- Guardian Link Via Invitation Code Functions
-- ============================================
-- These functions allow guardians to link to their children
-- using invitation codes generated by coaches/trainers
-- The codes are in format: TTV-XXX-YYY
-- ============================================

-- ============================================
-- Function 1: Validate invitation code and preview child
-- Used to show child info before confirming link
-- ============================================
CREATE OR REPLACE FUNCTION validate_guardian_invitation_code(
    p_code TEXT
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_code_record RECORD;
    v_player_profile RECORD;
BEGIN
    -- Normalize code (uppercase, trim)
    p_code := UPPER(TRIM(p_code));

    -- Find the code in invitation_codes table
    SELECT * INTO v_code_record
    FROM invitation_codes
    WHERE code = p_code
    AND (used = FALSE OR used IS NULL)
    AND (expires_at IS NULL OR expires_at > now())
    AND is_active = TRUE;

    IF NOT FOUND THEN
        -- Check if code exists but is invalid (for better error message)
        SELECT * INTO v_code_record
        FROM invitation_codes
        WHERE code = p_code;

        IF FOUND THEN
            IF v_code_record.used = TRUE THEN
                RETURN json_build_object('valid', FALSE, 'error', 'Code wurde bereits verwendet');
            ELSIF v_code_record.expires_at IS NOT NULL AND v_code_record.expires_at <= now() THEN
                RETURN json_build_object('valid', FALSE, 'error', 'Code ist abgelaufen');
            ELSIF v_code_record.is_active = FALSE THEN
                RETURN json_build_object('valid', FALSE, 'error', 'Code ist nicht mehr aktiv');
            END IF;
        END IF;

        RETURN json_build_object('valid', FALSE, 'error', 'Ungültiger Code');
    END IF;

    -- Check if code has a player_id (linked to offline player)
    IF v_code_record.player_id IS NOT NULL THEN
        -- Get player profile
        SELECT * INTO v_player_profile
        FROM profiles
        WHERE id = v_code_record.player_id;

        IF FOUND THEN
            RETURN json_build_object(
                'valid', TRUE,
                'child', json_build_object(
                    'id', v_player_profile.id,
                    'first_name', v_player_profile.first_name,
                    'last_name', v_player_profile.last_name,
                    'birthdate', v_player_profile.birthdate,
                    'avatar_url', v_player_profile.avatar_url
                ),
                'code_id', v_code_record.id
            );
        END IF;
    END IF;

    -- Code exists but no player linked - return code data for creating new profile
    RETURN json_build_object(
        'valid', TRUE,
        'child', json_build_object(
            'id', NULL,
            'first_name', v_code_record.first_name,
            'last_name', v_code_record.last_name,
            'birthdate', v_code_record.birthdate,
            'avatar_url', NULL
        ),
        'code_id', v_code_record.id,
        'needs_profile', TRUE
    );

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object(
        'valid', FALSE,
        'error', SQLERRM
    );
END;
$$;

-- ============================================
-- Function 2: Link guardian to child via invitation code
-- This validates the code, creates the link, and marks code as used
-- ============================================
CREATE OR REPLACE FUNCTION link_guardian_via_invitation_code(
    p_code TEXT
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_guardian_id UUID;
    v_code_record RECORD;
    v_child_profile RECORD;
    v_existing_link RECORD;
    v_child_id UUID;
BEGIN
    v_guardian_id := auth.uid();

    IF v_guardian_id IS NULL THEN
        RETURN json_build_object('success', FALSE, 'error', 'Nicht angemeldet');
    END IF;

    -- Normalize code
    p_code := UPPER(TRIM(p_code));

    -- Find valid code
    SELECT * INTO v_code_record
    FROM invitation_codes
    WHERE code = p_code
    AND (used = FALSE OR used IS NULL)
    AND (expires_at IS NULL OR expires_at > now())
    AND is_active = TRUE;

    IF NOT FOUND THEN
        RETURN json_build_object('success', FALSE, 'error', 'Ungültiger oder abgelaufener Code');
    END IF;

    -- Determine child ID
    IF v_code_record.player_id IS NOT NULL THEN
        -- Use existing offline player
        v_child_id := v_code_record.player_id;

        -- Get child profile
        SELECT * INTO v_child_profile
        FROM profiles
        WHERE id = v_child_id;

        IF NOT FOUND THEN
            RETURN json_build_object('success', FALSE, 'error', 'Spielerprofil nicht gefunden');
        END IF;
    ELSE
        -- Create new child profile from code data
        INSERT INTO profiles (
            first_name,
            last_name,
            birthdate,
            gender,
            club_id,
            sport_id,
            role,
            account_type,
            is_online,
            is_minor,
            guardian_id
        ) VALUES (
            v_code_record.first_name,
            v_code_record.last_name,
            v_code_record.birthdate::DATE,
            v_code_record.gender,
            v_code_record.club_id,
            v_code_record.sport_id,
            'player',
            'child',
            FALSE,
            TRUE,
            v_guardian_id
        )
        RETURNING * INTO v_child_profile;

        v_child_id := v_child_profile.id;
    END IF;

    -- Check if guardian is already linked to this child
    SELECT * INTO v_existing_link
    FROM guardian_links
    WHERE guardian_id = v_guardian_id
    AND child_id = v_child_id;

    IF FOUND THEN
        -- Mark code as used
        UPDATE invitation_codes
        SET used = TRUE, used_by = v_guardian_id, used_at = now()
        WHERE id = v_code_record.id;

        RETURN json_build_object(
            'success', TRUE,
            'child_id', v_child_id,
            'message', 'Du bist bereits als Vormund für dieses Kind registriert'
        );
    END IF;

    -- Create guardian link
    INSERT INTO guardian_links (
        guardian_id,
        child_id,
        relationship,
        is_primary,
        consent_given_at,
        consent_version
    ) VALUES (
        v_guardian_id,
        v_child_id,
        'parent',
        TRUE,
        now(),
        '1.0'
    );

    -- Mark code as used
    UPDATE invitation_codes
    SET used = TRUE, used_by = v_guardian_id, used_at = now()
    WHERE id = v_code_record.id;

    -- Update guardian's profile to mark as guardian if not already
    UPDATE profiles
    SET
        is_guardian = TRUE,
        account_type = CASE
            WHEN account_type = 'standard' THEN 'guardian'
            ELSE account_type
        END
    WHERE id = v_guardian_id;

    -- Update child's guardian_id reference if empty
    UPDATE profiles
    SET guardian_id = v_guardian_id
    WHERE id = v_child_id
    AND guardian_id IS NULL;

    RETURN json_build_object(
        'success', TRUE,
        'child_id', v_child_id,
        'child_name', COALESCE(v_child_profile.first_name, '') || ' ' || COALESCE(v_child_profile.last_name, ''),
        'message', 'Kind erfolgreich verknüpft'
    );

EXCEPTION WHEN OTHERS THEN
    RETURN json_build_object(
        'success', FALSE,
        'error', SQLERRM
    );
END;
$$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION validate_guardian_invitation_code TO authenticated;
GRANT EXECUTE ON FUNCTION link_guardian_via_invitation_code TO authenticated;

-- ============================================
-- Verification
-- ============================================
DO $$
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Guardian Invitation Code Functions Applied!';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Functions created:';
    RAISE NOTICE '  - validate_guardian_invitation_code (preview child from code)';
    RAISE NOTICE '  - link_guardian_via_invitation_code (link guardian via code)';
    RAISE NOTICE '========================================';
END $$;
